site_name: Proyecto Final
dev_addr: 127.0.0.1:8002
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
  - Documentación: index.md
  - Entrevista: Entrevista.md
copyright: ©GMDXX
site_author: GMDXX
